execution:
    uuid: 9ffefc1d-d05e-4e2e-bc07-4cfa20903e08
    runtime:
        start: 2021-04-04T07:58:15.998602+00:00
        end: 2021-04-04T07:58:20.273876+00:00
        duration: 4 seconds, and 275274 microseconds

action:
    type: import
    format: CasavaOneEightSingleLanePerSampleDirFmt
    manifest:
    -   name: ERR4656740_ERR4656740_L001_R1_001.fastq.gz
        md5sum: 4d3b4809dd67c742fc3b42b4763e4f99
    -   name: ERR4656741_ERR4656741_L001_R1_001.fastq.gz
        md5sum: c79a17b38ec2ac6b54f1a4cd1a01ef43
    -   name: ERR4656742_ERR4656742_L001_R1_001.fastq.gz
        md5sum: f059e4291dc9f9d469fa5d40611418e7
    -   name: ERR4656743_ERR4656743_L001_R1_001.fastq.gz
        md5sum: 7977c340e11755b3e9eb9f959e172d26
    -   name: ERR4656744_ERR4656744_L001_R1_001.fastq.gz
        md5sum: e4c6b00d633cdd2565967ce517d2de43
    -   name: ERR4656745_ERR4656745_L001_R1_001.fastq.gz
        md5sum: 0a6a231c12ae1879fdd156330a7f8e4a
    -   name: ERR4656746_ERR4656746_L001_R1_001.fastq.gz
        md5sum: 26024c98c3f4a517a91c6b1d4cc2bf66
    -   name: ERR4656747_ERR4656747_L001_R1_001.fastq.gz
        md5sum: d324be6458adf6d0b36430d0dbdd14d0
    -   name: ERR4656748_ERR4656748_L001_R1_001.fastq.gz
        md5sum: 379de7b4a1eaa105298a4451f7a487fb
    -   name: ERR4656749_ERR4656749_L001_R1_001.fastq.gz
        md5sum: 8531c9dab729ad10d84c6918550b0e9e

transformers:
    output:
    -   from: CasavaOneEightSingleLanePerSampleDirFmt
        to: SingleLanePerSampleSingleEndFastqDirFmt
        plugin: !ref 'environment:plugins:types'

environment:
    platform: linux-x86_64
    python: |-
        3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)
        [GCC 7.3.0]
    framework:
        version: 2020.8.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2020.8.0|0'
    plugins:
        types:
            version: 2020.8.0
            website: https://github.com/qiime2/q2-types
    python-packages:
        zipp: 3.1.0
        xopen: 0.9.0
        widgetsnbextension: 3.5.1
        wheel: 0.35.1
        webencodings: 0.5.1
        wcwidth: 0.2.5
        urllib3: 1.25.10
        unifrac: 0.10.0
        tzlocal: '2.1'
        typing-extensions: 3.7.4.2
        traitlets: 4.3.3
        tornado: 6.0.4
        toml: 0.10.1
        threadpoolctl: 2.1.0
        testpath: 0.4.4
        terminado: 0.8.3
        statsmodels: 0.11.1
        six: 1.15.0
        setuptools: 49.6.0.post20201009
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.10.1
        scipy: 1.5.2
        scikit-learn: 0.23.1
        scikit-bio: 0.5.5
        requests: 2.24.0
        qiime2: 2020.8.0
        q2templates: 2020.8.0
        q2cli: 2020.8.0
        q2-vsearch: 2020.8.0
        q2-types: 2020.8.0
        q2-taxa: 2020.8.0
        q2-sample-classifier: 2020.8.0
        q2-quality-filter: 2020.8.0
        q2-quality-control: 2020.8.0
        q2-phylogeny: 2020.8.0
        q2-metadata: 2020.8.0
        q2-longitudinal: 2020.8.0
        q2-gneiss: 2020.8.0
        q2-fragment-insertion: 2020.8.0
        q2-feature-table: 2020.8.0
        q2-feature-classifier: 2020.8.0
        q2-emperor: 2020.8.0
        q2-diversity: 2020.8.0
        q2-diversity-lib: 2020.8.0
        q2-demux: 2020.8.0
        q2-deblur: 2020.8.0
        q2-dada2: 2020.8.0
        q2-cutadapt: 2020.8.0
        q2-composition: 2020.8.0
        q2-alignment: 2020.8.0
        pyzmq: 19.0.2
        PyYAML: 5.3.1
        pytz: '2020.1'
        python-dateutil: 2.8.1
        pytest: 6.0.1
        PySocks: 1.7.1
        pyrsistent: 0.16.0
        pyparsing: 2.4.7
        pyOpenSSL: 19.1.0
        Pygments: 2.6.1
        pycparser: '2.20'
        py: 1.9.0
        ptyprocess: 0.6.0
        psutil: 5.7.2
        prompt-toolkit: 3.0.6
        prometheus-client: 0.8.0
        pluggy: 0.13.1
        pip: 20.2.2
        Pillow: 7.2.0
        pickleshare: 0.7.5
        pexpect: 4.8.0
        patsy: 0.5.1
        parso: 0.7.1
        pandocfilters: 1.4.2
        pandas: 0.25.3
        packaging: '20.4'
        olefile: '0.46'
        numpy: 1.19.1
        notebook: 6.1.3
        nose: 1.3.7
        networkx: '2.4'
        nbformat: 5.0.7
        nbconvert: 5.6.1
        natsort: 7.0.1
        msgpack: 1.0.0
        more-itertools: 8.4.0
        mistune: 0.8.4
        matplotlib: 3.2.2
        MarkupSafe: 1.1.1
        lockfile: 0.12.2
        kiwisolver: 1.2.0
        jupyter-core: 4.6.3
        jupyter-client: 6.1.6
        jsonschema: 3.2.0
        joblib: 0.16.0
        Jinja2: 2.11.2
        jedi: 0.17.2
        ipywidgets: 7.5.1
        ipython: 7.16.1
        ipython-genutils: 0.2.0
        ipykernel: 5.3.4
        iniconfig: 1.0.1
        importlib-metadata: 1.7.0
        ijson: 3.1.1
        idna: '2.10'
        hdmedians: '0.13'
        h5py: 2.10.0
        gneiss: 0.4.6
        future: 0.18.2
        fastcluster: 1.1.26
        entrypoints: '0.3'
        emperor: 1.0.1
        dnaio: 0.4.2
        DendroPy: 4.4.0
        defusedxml: 0.6.0
        decorator: 4.4.2
        deblur: 1.1.0
        Cython: 0.29.21
        cycler: 0.10.0
        cutadapt: '2.10'
        cryptography: '3.0'
        click: 7.1.2
        chardet: 3.0.4
        cffi: 1.14.1
        certifi: 2020.6.20
        CacheControl: 0.12.6
        brotlipy: 0.7.0
        bokeh: 2.1.1
        bleach: 3.1.5
        biom-format: 2.1.8
        bibtexparser: 1.1.0
        backports.functools-lru-cache: 1.6.1
        backcall: 0.2.0
        attrs: 20.1.0
        argon2-cffi: 20.1.0
